name: lando-events
services:
  node:
    type: node:20
    build:
      - npm run install
    scanner: false
    ssl: false
    sslExpose: false
    overrides:
      ports:
        - 8022:8022
tooling:
  node:
    service: node
  npm:
    service: node
  dev:
    service: node
    cmd: npm run dev --port 8022
    env:
      DEBUG: "@lando/*"
      VITE_GMAPS_API_KEY: APIKEY
