[build]
  base = "./"
  publish = "_site"
  command = "yarn build"
  
# Sets our asset optimization
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = false
[build.processing.images]
  compress = true

# Caches our images for 1 year
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    
    
# Redirect to canonical location
[[redirects]]
  from = "https://events.devwithlando.io"
  to = "https://lando.dev/events"
  status = 301
  force = true
[[redirects]]
  from = "https://events.devwithlando.io/"
  to = "https://lando.dev/events"
  status = 301
  force = true
[[redirects]]
  from = "https://events.devwithlando.io/*"
  to = "https://lando.dev/events/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://events.lando.dev"
  to = "https://lando.dev/events"
  status = 301
  force = true
[[redirects]]
  from = "https://events.lando.dev/"
  to = "https://lando.dev/events"
  status = 301
  force = true
[[redirects]]
  from = "https://events.lando.dev/*"
  to = "https://lando.dev/events/:splat"
  status = 301
  force = true
 [[redirects]]
  from = "https://events.lndo.io/"
  to = "https://lando.dev/events"
  status = 301
  force = true
[[redirects]]
  from = "https://events.lndo.io"
  to = "https://lando.dev/events"
  status = 301
  force = true
[[redirects]]
  from = "https://events.lndo.io/*"
  to = "https://lando.dev/events/:splat"
  status = 301
  force = true

# Rewrites
[[redirects]]
  from = "/"
  to = "/blog"
  status = 200
[[redirects]]
  from = "/events/*"
  to = "/:splat"
  status = 200
